name: Build

on:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: MatrixApp.apk
          path: ./bin/*.apk
