name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          java-version: '11'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-pip unzip wget git
          pip install --upgrade pip
          pip install buildozer cython

      # Install Android SDK command line tools
      - name: Install Android SDK command line tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8502050_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          rm commandlinetools.zip

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      # Install Android SDK components
      - name: Install Android SDK components
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-31" "tools" "aidl"

      # Run Buildozer to build the APK
      - name: Build APK
        run: |
          buildozer android debug

      # Upload APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MatrixApp.apk
          path: ./bin/*.apk
