name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y buildozer python3-pip openjdk-8-jdk unzip
          pip install --upgrade pip
          pip install buildozer cython virtualenv
      - run: buildozer -v android debug
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: app-debug.apk
          path: bin/app-debug.apk
