name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: stable
          args: 'android debug deploy run log_level=2'
          workdir: '.'  # Pastikan direktori kerja diatur dengan benar jika ada di folder tertentu

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MatrixApp.apk
          path: ./bin/*.apk
