name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-pip git openjdk-11-jdk zip unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MatrixApp.apk
          path: bin/*.apk
